import type { Metadata } from 'next'

import { Navbar } from '~/components'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navbar />
      <p>Frontend Layout</p>
      {children}
    </>
  )
}
